# docker-compose.yml
# This file defines the services that make up the app.
# VERSION 2: Corrected volume paths for Umbrel compatibility.

version: "3.7"

services:
  # The VPN container. All network traffic will go through here.
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: qbittorrent-vpn-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      # CORRECTED: Mapped to the app's specific data directory.
      - ${APP_DATA_DIR}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${OPENVPN_PROTOCOL}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CITIES=${SERVER_CITIES}
      - PUID=1000
      - PGID=1000
      - VPN_LAN_NETWORK=192.168.0.0/16
    restart: unless-stopped

  # The qBittorrent container.
  qbittorrent:
    image: hotio/qbittorrent:latest
    container_name: qbittorrent-vpn-app
    network_mode: "service:vpn"
    depends_on:
      - vpn
    volumes:
      # CORRECTED: Mapped to the app's specific data directory.
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/downloads:/data
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    restart: unless-stopped
```

### Next Steps

1.  **Update the File:** Replace the content of `diseric-qbittorrent-vpn/docker-compose.yml` in your GitHub repository with the code from the Canvas above.
2.  **Commit and Push:** Save and push the change to your GitHub repository.
3.  **Refresh in Umbrel:**
    * Go to the App Store > Community App Stores.
    * **Remove** "Diseric's App Store".
    * **Add it back** with the same URL.

This should fix the parsing error and allow you to install the a
