services:
  app_proxy:
    environment:
      APP_HOST: qbittorrent
      APP_PORT: 8080

  qbittorrent:
    image: hotio/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - ${APP_DATA_DIR}/config:/config
    restart: unless-stopped
